### ISSUE TITLE
Undefined symbols juce::MathConstants<float>::twoPi

### ISSUE THREAD

**Issue by xiaohua717** [AndrewJJ/DSP-Testbench#1]
when i compile and build this project, it reported the following error：
```
Undefined symbols for architecture arm64:
  "juce::MathConstants<float>::twoPi", referenced from:
      juce::dsp::PolyBlepOscillator<float>::initialise(unsigned long) in SourceComponent.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by AndrewJJ** [comment]
Hi - I don't have access to an M1 Mac to test this but I suspect it may be due to the long double literals in JUCE\modules\juce_core\maths\juce_MathsFunctions.h. Can you build after deleting the L on the end of the doubles at lines 382, 385, 388, 391, 394?

This article may be of interest: https://developer.arm.com/documentation/ka004751/1-0?lang=en&rev=3

**Comment by HMWDLG** [comment]
I delete the L in JUCE\modules\juce_core\maths\juce_MathsFunctions.h but still error.
iMac 2019

Undefined symbols for architecture x86_64:
  "juce::MathConstants<float>::twoPi", referenced from:
      juce::dsp::PolyBlepOscillator<float>::initialise(unsigned long) in SourceComponent.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by AndrewJJ** [comment]
Without access to an M1 Mac I can't really help other than to suggest the following:

- try swapping the literals for float values in the juce file
- try defining the long double for 2 pi without the multiplication, i.e. 6.283185307179586477L
- use the literal instead of the juce math constant in PolyBLEP.h
- ask for help on the JUCE forum

**Comment by HMWDLG** [comment]
> 

Thanks a lot!
